pipeline:
  identifier: Build_go_pipeline_sample_1699265036780
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: Sampleproject
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1699264997537
        repoName: akavakon72/go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    shell: Sh
                    command: go test
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
