pipeline:
  identifier: Build_go_pipeline_sample_1699260059533
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: Sampleproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699260043843
        repoName: go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    command: go test -v ./...
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Success
                  identifier: Success
                  spec:
                    shell: Sh
                    command: echo "success"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
